name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      release_message:
        type: string
        description: Release message
        required: true
      prerelease:
        type: boolean
        description: Is this a pre-release version?
        required: false
        default: false

permissions:
  contents: write

jobs:
  extract-version:
    name: Extract Version Number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_extraction.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install toml
        run: pip install toml
      - id: version_extraction
        run: cd extractor-sdk && echo "version=$(python -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])')" >> $GITHUB_OUTPUT

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - extract-version
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ needs.extract-version.outputs.version }}"
          prerelease: ${{ github.event.inputs.prerelease }}
          body: ${{ github.event.inputs.release_message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  publish-extractor-sdk-to-pypi:
    name: Publish Extractor SDK
    runs-on: ubuntu-latest
    needs:
      - create-release
    environment:
      name: pypi
      url: https://pypi.org/p/indexify-extractor-sdk/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: python3 -m pip install poetry --user
      - name: Build Packages
        run: cd extractor-sdk && python3 -m poetry build
      - name: Publish Extractor SDK to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: extractor-sdk/dist/
